#!/bin/sh
# title=Format SD Card (FAT32)
# desc=Format the external sd card [fat32]. This is DANGEROUS, all content in sd card will be erased.

echo "Formating SD Card"
mkfs -t vfat /dev/mmcblk1p1
echo "Formating finished"
echo "END"

