#!/bin/sh
# title=Format SD Card (EXT3)
# desc=Format the external sd card [ext3]. This is DANGEROUS, all content in sd card will be erased.

echo "Formating SD Card"
mkfs -t ext3 /dev/mmcblk1p1
echo "Formating finished."
echo "END"

