#!/bin/sh
# title=Format SD Card (EXT4) CAUTION!
# desc=Format the external sd card [ext4]. This is DANGEROUS, all content in sd card will be erased.

echo "Umounting SD Card"
umount -f /media/sdcard
echo "Erasing and partitioning SD Card"
echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/mmcblk1
echo "Formating SD Card"
mkfs -t ext4 /dev/mmcblk1p1
echo "Formating finished"
echo "Mounting SD Card"
mkdir /media/sdcard
mount /dev/mmcblk1p1 /media/sdcard
chmod 0777 -R /media/sdcard
echo "END"

