#!/bin/sh
# title=Format SD Card (EXT4)
# desc=Format the external sd card [ext4]. Save the content before the process, sd card will be erased.

echo "Formating deactivated"
echo "mkfs -t ext4 /dev/mmcblk1p1"
echo "Finish"

