#!/bin/sh
# title=Format SD Card (FAT32) CAUTION!
# desc=Format the external sd card [fat32]. This is DANGEROUS, all content in sd card will be erased.

echo "Umounting SD Card"
umount -f /media/sdcard
echo "Erasing and partitioning SD Card"
echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/mmcblk1
echo "Formating SD Card"
mkfs -t vfat /dev/mmcblk1p1
echo "Formating finished"
echo "END"

