#!/bin/sh
# title=Format SD Card (EXT4)
# desc=Format the external sd card [ext4]. This is DANGEROUS, all content in sd card will be erased.

echo "Formating SD Card"
mkfs -t ext4 /dev/mmcblk1p1
echo "Formating finished"
echo "END"

