#!/bin/sh
# title=Restore gmenu2x sections
# desc=Create default sections in gmenu2x and restore missings apps included in firmware.

cp -r /usr/share/gmenu2x/sections/* /usr/local/home/.gmenu2x/sections

